using System;
using System.Security.Cryptography;

namespace TamperProofUnitTests
{
    // Code generated by TamperProofCoder.CodeFactory
    public class TestValidator : Willowsoft.TamperProofData.Validator
    {
        protected override RSAParameters GetPublicKey()
        {
            RSAParameters rsap = new RSAParameters();
            rsap.Exponent = new byte[] { 1, 0, 1 };
            rsap.Modulus = new byte[] { 175, 94, 24, 136, 157, 16, 212, 22, 170, 144, 26, 199, 67, 162, 125, 5,
              241, 164, 134, 178, 146, 124, 64, 80, 66, 42, 110, 10, 196, 121, 98, 169,
              22, 104, 240, 151, 171, 29, 1, 230, 85, 204, 137, 247, 98, 160, 186, 205,
              251, 32, 62, 224, 187, 207, 112, 218, 6, 148, 115, 2, 179, 224, 245, 71,
              250, 5, 24, 103, 91, 165, 33, 243, 249, 97, 3, 150, 89, 169, 184, 242,
              161, 39, 237, 84, 12, 45, 80, 169, 242, 253, 98, 167, 157, 176, 77, 209,
              180, 2, 125, 228, 222, 146, 189, 191, 5, 222, 3, 25, 147, 55, 233, 148,
              71, 248, 153, 156, 159, 173, 16, 166, 83, 44, 16, 210, 181, 15, 208, 9 };
            return rsap;
        }
    }
}
